ALTER TABLE public.device_data
ADD COLUMN IF NOT EXISTS door_open smallint NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS touch1 smallint NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS touch2 smallint NOT NULL DEFAULT 0;